pipelines:
  default:
      - step:
          name: Installing deps - config env
          script:
            - echo "hola"
          services:
            - docker

      - step:
          name: Lint
          script:
            - echo "[+] Lint Step"

      - step:
          name: "dockerbuild"
          script:
            # - apt update
            - wget -O kubectl https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl
            - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            - wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip"
            - unzip awscliv2.zip
            - ./aws/install
            - export DOCKER_BUILDKIT=1
            # - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
            - /usr/local/bin/aws ecr get-login-password
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password $(aws ecr get-login-password --region us-east-1) 381492015278.dkr.ecr.us-east-1.amazonaws.com
            - echo $AWS_ECR_ENDPOINT/$AWS_DOCKER_TAG
            - docker build . -t $AWS_ECR_ENDPOINT/$AWS_DOCKER_TAG
            # - docker-compose build
            # - docker -t $AWS_ECR_ENDPOINT/$AWS_DOCKER_TAG tenancy-broker360_web:latest
            - /usr/local/bin/aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_K8S_CLUSTER
            - docker push $AWS_ECR_ENDPOINT/$AWS_DOCKER_TAG
            - kubectl delete -f deploy/final-localhost-tenancy360.yaml
            - kubectl apply -f deploy/final-localhost-tenancy360.yaml
          services:
            - docker

      - step:
          name: Push docker image
          script:
            - echo "Hola"
            # - docker push $AWS_ENDPOINT/$AWS_DOCKER_TAG
          services:
            - docker